[package]
name = "m-notes-desktop"
version = "1.0.0"
description = "M Notes Desktop for Windows"
authors = ["Is-Lingling"]
edition = "2021"

[dependencies]
tauri = { version = "2.11", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = { version = "2.6", features = [] }
